name: base
channels: 
  - conda-forge
dependencies:
  - pip
  - numpy
  - cudatoolkit=11.1.1
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - pandas
    - Pillow
    - matplotlib
    - cython
    - pykdtree
    - torch==1.8.0+cu111 
    - torchvision==0.9.0+cu111
    - hydra-core==1.2
    - trimesh==3.9
    - networkx
    - wandb
    - simple-3dviz
    - scipy
    - pyquaternion
    - PyVirtualDisplay
